# Generated by Django 4.2.14 on 2024-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost", name="slug", field=models.SlugField(null=True),
        ),
    ]
